# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Nox' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nox
  pod 'KosherCocoa', '~> 3.0'
  pod 'GradientView'
end
